### ISSUE TITLE
draw.trajectory.heatmap does not accept a matrix

### ISSUE THREAD

**Issue by Zouter** [rcannood/SCORPIUS#1]
Gives this error:

```
Error in annotation_colors[[colnames(annotation)[i]]] : 
  subscript out of bounds
```

**Comment by rcannood** [comment]
Could you provide an example and/or some data? In the example below, `expr.tafs` is a matrix, and the `draw.trajectory.heatmap` function works.
```
> dataset <- generate.dataset(type="s", num.genes=500, num.samples=1000, num.groups=4)
> expression <- dataset$expression
> dist <- correlation.distance(expression)
> space <- reduce.dimensionality(dist, ndim=2)
> groups <- dataset$sample.info$group.name
> traj <- infer.trajectory(space)
> time <- traj$time
> tafs <- find.trajectory.aligned.features(expression, time)
> expr.tafs <- expression[,tafs$tafs]
> 
> draw.trajectory.heatmap(expr.tafs, time)
> is.matrix(expr.tafs)
[1] TRUE
```

**Comment by Zouter** [comment]
[testdata.RData.zip](https://github.com/rcannood/SCORPIUS/files/104703/testdata.RData.zip)

Eplot is the expression matrix. It works if I do as.data.frame(Eplot)

**Comment by Zouter** [comment]
I think I found the issue, my matrix did not have any rownames and the as.data.frame function gave him rownames as a side effect. So a simple test if their are rownames should do the trick :+1:
