### ISSUE TITLE
Use discrete colormaps for plots

### ISSUE THREAD

**Issue by siddharthst** [rcannood/SCORPIUS#12]
Is there a way to instruct Scorpius to use discrete colourmaps for groups in `draw_trajectory_heatmap` and `draw_trajectory_plot` - the current colour palette is not convenient for > 10 groups!
Something akin to this:
![Screenshot 2019-03-12 at 3 33 52 PM](https://user-images.githubusercontent.com/37268732/54208485-4e613c80-44dc-11e9-9f23-599c1a106273.png)
from this:
![Screenshot 2019-03-12 at 3 33 08 PM](https://user-images.githubusercontent.com/37268732/54208491-528d5a00-44dc-11e9-8737-a75aa9410453.png)

**Comment by rcannood** [comment]
Hello @siddharthst ! Thanks for your suggestion. It is an important issue, though not a trivial one to tackle. For `draw_trajectory_plot()`, this can already be achieved by converting your progression group into a factor with the correct levels and adding a custom colour scale to it with `draw_trajectory_plot(...) + scale_colour_manual(values = ...)`.

I will look for a better solution that can handle both continuous (#13) and discrete colour schemes for both `draw_trajectory_plot()` and `draw_trajectory_heatmap()`.

**Comment by rcannood** [comment]
Hello again. In the devel branch of SCORPIUS, I have added an extra parameter in order for you to be able to specify the palette manually. Below is an example. Does this solve your problem?

```R
# install the devel branch with: devtools::install_github("rcannood/SCORPIUS@devel")
library(SCORPIUS)

dataset <- generate_dataset(num_genes = 100, num_samples = 120, num_groups = 12)
groups <- factor(gsub("Group ", "", dataset$sample_info$group_name), levels = 1:12)

space <- reduce_dimensionality(dataset$expression, ndim = 2)
traj <- infer_trajectory(space)
draw_trajectory_plot(space, progression_group = groups, path = traj$path)

palette <- 
  setNames(
    c(
      RColorBrewer::brewer.pal(4, "Blues"),
      RColorBrewer::brewer.pal(4, "Oranges"),
      RColorBrewer::brewer.pal(4, "Greens")
    ),
    1:12
  )

draw_trajectory_plot(space, progression_group = groups, path = traj$path, progression_group_palette = palette)

draw_trajectory_heatmap(dataset$expression, traj$time, progression_group = groups, progression_group_palette = palette)
```

**Comment by siddharthst** [comment]
Yup, it does solve the problem!

**Comment by rcannood** [comment]
That's great to hear! 

At some point, this version of SCORPIUS will make it to CRAN. For now, you can keep using the devel version, if you like.
