### ISSUE TITLE
Use continuous color gradient for points

### ISSUE THREAD

**Issue by SteveBoothHLI** [rcannood/SCORPIUS#13]
Hi there, I really like SCORPIUS, great job!

Is there a way to color the points in the trajectory plot based on continuous variables rather than grouping them into discrete categories? Such as using a continuous color gradient etc?...

Best,
Steve

**Comment by rcannood** [comment]
Hey Steve, thanks for pointing this out. I will look for an adequate solution and get back to you.

**Comment by SteveBoothHLI** [comment]
Thanks for the quick response! Alternatively users can replot the data from reduce_dimensionality, color the points however needed (used continuous viridis here), and overlay the scorpius trajectory line as follows:
`
### Reduce dimensionality ###
space <- reduce_dimensionality(MR_expr, correlation_distance)
### Traj inference ###
traj <- infer_trajectory(space)
draw_trajectory_plot(space, progression_group=NULL ,traj$path, contour = FALSE)
#### Replot in ggplot with coloring for continuous variables ## 
space2 <- as.data.frame(space)

gg <- ggplot(space2, aes(x=Comp1, y=Comp2, color = pDat_MR$LM)) +  
  geom_point(size=2) +  scale_color_viridis(discrete = FALSE) +
  guides(colour=guide_legend(override.aes=list(size=6))) +
   scale_x_continuous(limits = c(-0.6, 0.6))+ scale_y_continuous(limits = c(-0.6, 0.6))+
  theme_classic() +  geom_path(data=as.data.frame(traj$path),aes(x=Comp1, y=Comp2), size = 1, color = "black")
gg

grid.arrange(
  gg + scale_color_viridis(option="A") + labs(x="Virdis A", y=NULL),
  gg + scale_color_viridis(option="B") + labs(x="Virdis B", y=NULL),
  gg + scale_color_viridis(option="C") + labs(x="Virdis C", y=NULL),
  gg + scale_color_viridis(option="D") + labs(x="Virdis D", y=NULL),
  gg + scale_color_viridis(option="E") + labs(x="Virdis E", y=NULL),
  ncol=3, nrow=2
)`

**Comment by rcannood** [comment]
In the devel branch of SCORPIUS, I added parameters to `draw_trajectory_plot()` and `draw_trajectory_heatmap()` that will allow you to define a palette with the `progression_group` and `progression_group_palette` parameters. By now, the name should be changed, however.

Example:
``` R
# first run: devtools::install_github("rcannood/SCORPIUS@devel")
dataset <- generate_dataset(num_genes = 500, num_samples = 300, num_groups = 4)
space <- reduce_dimensionality(dataset$expression, ndim = 2)
draw_trajectory_plot(space, progression_group = dataset$expression[,1])
``` 

Does this work for you?

**Comment by rcannood** [comment]
In the meantime, the changes have been pushed to CRAN. If you have further questions, feel free to reopen this issue.
