### ISSUE TITLE
Gene expression on trajectory plot

### ISSUE THREAD

**Issue by lc822** [rcannood/SCORPIUS#15]
Hi,

I was wondering whether there is a way to plot the expression of a gene on the trajectory plot?  Additionally, is it possible to draw a line graph showing the expression of a particular gene along the pseudotime axis?

Many thanks for the help.

Best wishes,
Lucy

**Comment by rcannood** [comment]
Hello Lucy!

> I was wondering whether there is a way to plot the expression of a gene on the trajectory plot? 

Certainly! I will demonstrate using the example dataset:
```r
library(SCORPIUS)
data(ginhoux)
expression <- ginhoux$expression
group_name <- ginhoux$sample_info$group_name
space <- reduce_dimensionality(expression)
traj <- infer_trajectory(space)
draw_trajectory_plot(space, group_name, traj$path)
ggsave("~/example1.png", width = 5, height = 4)
```
![example1](https://user-images.githubusercontent.com/553642/66304550-c28e8200-e8fd-11e9-9745-b7084543d48a.png)
You simply provide your expression data to the `progression_group` parameter of the draw function. I should change the documentation to clarify that you can also use that parameter for continuous values such as expression. 
```r
draw_trajectory_plot(space, expression[,"Mpo"], traj$path) + labs(colour = "Mpo\nexpression")
ggsave("~/example2.png", width = 5, height = 4)
```
![example2](https://user-images.githubusercontent.com/553642/66304701-2153fb80-e8fe-11e9-9f3a-4c25b9938517.png)

> Additionally, is it possible to draw a line graph showing the expression of a particular gene along the pseudotime axis?

Is the following what you mean? As you can see, it's not implemented into SCORPIUS, though I could easily add it, if you like. For now, you can use the following ggplot2 code.
```r
library(ggplot2)
expression_df <- data.frame(
  pseudotime = traj$time,
  group_name = group_name,
  expression
)
ggplot(expression_df) +
  geom_point(aes(pseudotime, Mpo, colour = group_name)) +
  theme_classic() +
  scale_colour_brewer(palette = "Set1") +
  labs(x = "Pseudotime", y = "Mpo expression", colour = "Group")
ggsave("~/example3.png", width = 5, height = 4)
```
![example3](https://user-images.githubusercontent.com/553642/66304907-8b6ca080-e8fe-11e9-867a-0f4238403768.png)

Kind regards,
Robrecht

**Comment by lc822** [comment]
Hi Robrecht,

These graphs are perfect thank you!  

Sorry, can I just ask a naive question - should the expression matrix used as input be a raw UMI counts matrix or a normalized expression matrix?

I have 10x data which I have processing using the Seurat pipeline with SCT normalisation.  Which slot should I use:
sample@assays$RNA@counts    # raw UMI counts
sample@assays$SCT@data     # normalized data
sample@assays$SCT@scale.data    # normalized and scaled data

Many thanks,
Lucy

**Comment by rcannood** [comment]
Use the normalised data :) Don't forget to transpose the matrix.

**Comment by zouter** [comment]
Just to add, I suggest using `sample@assays$SCT@data` because this is still a sparse matrix, and thus more memory efficient. SCORPIUS will scale internally whenever needed

**Comment by rcannood** [comment]
Oh, that's absolutely true! If you have a large dataset, its be best to use the following.

```r
expression <- Matrix::t(sample@assays$SCT@data)
space <- reduce_dimensionality(expression)
traj <- infer_trajectory(space)
```

Indeed, using the scaled matrix is not necessary because `reduce_dimensionality()` uses a rank-correlation, which is scale invariant.

**Comment by lc822** [comment]
Thank you both!
