### ISSUE TITLE
Trajectory and Pseudotime on SEURAT v3 dataset

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [rcannood/SCORPIUS#16]
Hi there,
thank you for having developed this tool.
i'd use my data (60k cells) analysed with seurat v3 in scorpius. it' possible analyse this large dataset with our tool?
any suggestion for how extract my data from seurat object?

kind regards,
Domenico

**Comment by lc822** [comment]
Hi,

I'm not one of the developers but you should be able to extract the data as follows:

```
expression <- as.matrix(t(sample@assays$SCT@data))      # normalised expression matrix
group_name <- sample@meta.data[, which(colnames(sample@meta.data) == seurat_clusters)]      # extract the column from the metadata table that contains the cluster assignments
```

"sample" is the name of the Seurat object.
If you didn't use sctransform, "SCT" can be replaced with "RNA".

Best wishes,
Lucy

**Comment by rcannood** [comment]
Hello Domenico and Lucy,

Thanks, Lucy, for already replying to Domenico.

Indeed, you can use SCORPIUS to analyse your dataset in this way. Plotting a heatmap will not be possible for 60k cells, but I'm working on a solution for this. I'll also provide a vignette for working with data from Seurat.

Does the code provided by Lucy work for you?

Kind regards,
Robrecht

**Comment by DomenicoSkyWalker89** [comment]
Thanks Lucy and Robrecht for your time.
The code above works correctly. I'm waiting for a vignette for Seurat Data.
I'm also interested in split the data for condition  or time and compare the difference on trajectory. Think it's possible do it?
Thanks a lot.

Best,
Domenico

**Comment by rcannood** [comment]
Hello Domenico,

You can find a vignette for running SCORPIUS on a Seurat object [here](https://github.com/rcannood/SCORPIUS/blob/devel/vignettes/seurat.md).

I'm not sure I understand your second question. Do you wish to run two SCORPIUS analyses depending on the condition?

Kind regards,
Robrecht

**Comment by DomenicoSkyWalker89** [comment]
Hi Robrecht,
thanks a lot for the vignette, i will use SCORPIUS this Monday.
Regarding the second question, my Data are composed as follow, two groups (R and NR) and for each group three time points (T0,T1,T2). I would run one SCORPIUS using all cells and then split the trajectory graph for groups or time points to see the difference.

Kind regards,
Domenico

**Comment by DomenicoSkyWalker89** [comment]
Hi Robrecht,
I analyzed my data using SCORPIUS but there is something wrong (I think).
This data contain only CD8+ T cells, as you can see on UMAP i have several cluster representing different subpopulation (Naive, effector etc...).

Have you any suggestions as to why there are two main groups of cells on SCORPIUS?
I expect to see trajectory of different differentiation steps, right?

Kind regards,
Domenico
 
![umap](https://user-images.githubusercontent.com/53559811/72967885-a20e0900-3dc2-11ea-90c7-5fed9b5a6d0b.jpeg)



![scorpius](https://user-images.githubusercontent.com/53559811/72967368-7a6a7100-3dc1-11ea-9121-d03ea4e40858.jpeg)
![heatmap_scorpius](https://user-images.githubusercontent.com/53559811/72967378-7fc7bb80-3dc1-11ea-9e2e-1b0dfc14fc50.jpeg)
