### ISSUE TITLE
Run SCORPIUS on data with batch effects?

### ISSUE THREAD

**Issue by lc822** [rcannood/SCORPIUS#17]
Hi,

Thanks for the really great package.

I have 10x data from TCR-stimulated T cells from three donors and have performed a merged analysis of these in Seurat.  There are some batch effects due to donor and I have generated corrected PCA embeddings using Harmony.  I would like to run SCORPIUS on the merged data, so that I can get a single trajectory and heatmap illustrating the activation pathway, rather than one trajectory per donor.  

Is it possible to incorporate batch effects into SCORPIUS, as I know it uses its own method for dimensionality reduction? 

Many thanks,
Lucy

**Comment by rcannood** [comment]
Hmm. Any batch effects should be taken care of prior to running SCORPIUS. If you have a dimensionality reduction method that takes batch effects into account, you can opt to use that instead of the dimensionality reduction provided by SCORPIUS :)

**Comment by rcannood** [comment]
I hope this solved your problem. If not, feel free to reply to this issue or open a new one.

**Comment by lucygarner** [comment]
@rcannood, I was wondering whether you have tried running SCORPIUS with corrected counts e.g. from Seurat integration?
