### ISSUE TITLE
Error when trying to change the colour for draw_trajectory_heatmap

### ISSUE THREAD

**Issue by lc822** [rcannood/SCORPIUS#18]
Hi,

Could you please help me with changing the colours in draw_trajectory_heatmap?

My progression_group is a factor with two levels.

I tried the following:
`my_colour_palette <- c("red", "blue")`
`draw_trajectory_heatmap(expr_sel, traj$time, progression_group = stimulation_group, modules, show_labels_row = TRUE, progression_group_palette = my_colour_palette)`

However, I am getting the following error:
`Error in convert_annotations(annotation_col, annotation_colors) : 
  Factor levels on variable Progression do not match with annotation_colors`

How can I solve this?  

I would also like to reverse the "time" colours on the heatmap, as I am looking at cell activation at the trajectory is currently going from activated to non-activated cells, and I would like it to go from non-activated to activated cells.

Many thanks,
Lucy

**Comment by rcannood** [comment]
Hello Lucy! 

This is because `my_colour_palette` should be named with the unique values in `stimulation_group`. For example:
```r
library(tidyverse)
library(SCORPIUS)

dataset <- generate_dataset(num_genes = 500, num_samples = 1000, num_groups = 2)
group_name <- dataset$sample_info$group_name
space <- reduce_dimensionality(dataset$expression, ndim = 2)
traj <- infer_trajectory(space)

gimp <- gene_importances(dataset$expression, traj$time)
gene_sel <- gimp[1:50,]
expr_sel <- dataset$expression[,gene_sel$gene]
modules <- extract_modules(scale_quantile(expr_sel), traj$time, verbose = FALSE)

my_colour_palette <- c("Group 1" = "red", "Group 2" = "blue")
draw_trajectory_heatmap(
  expr_sel, 
  traj$time,
  progression_group = group_name,
  modules, 
  show_labels_row = TRUE,
  progression_group_palette = my_colour_palette
)
```

I added a more useful error message when the names are accidentally omitted (1c52c4e16c7cf2e7ec8320566b36d37e7c9a07b3).

Does this solve your problem?

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue as it seems to be solved. If this is not the case, feel free to respond to this issue again.
