### ISSUE TITLE
Revert the order of cells in draw_trajectory_heatmap

### ISSUE THREAD

**Issue by lc822** [rcannood/SCORPIUS#19]
Hi,

I was wondering whether it is possible to revert the order of the cells in draw_trajectory_heatmap, so that the cells currently on the left of the heatmap end up on the right, and vice versa?

Many thanks,
Lucy

**Comment by rcannood** [comment]
Hello Lucy! 

If your trajectory is in the wrong direction, you can use the `reverse_trajectory()` command to reverse it:

```r
traj <- infer_trajectory(space)
reverse_traj <- reverse_trajectory(traj)
draw_trajectory_heatmap(...)
```

Does this work for you?

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue as it seems to be solved. If this is not the case, feel free to respond to this issue again.

**Comment by lc822** [comment]
Thanks, this seems to have worked. Sorry for the very late response!
