### ISSUE TITLE
meaningful of the trajectory direction

### ISSUE THREAD

**Issue by sherriying** [rcannood/SCORPIUS#21]
Hi there, 

Thanks for developing the nice TI package. I just start to learn how to use SCORPIUS and interpret the result from the analysis. 
I am wondering if the direction of the trajectory is meaningful after running inference analysis? I have two datasets corresponding to the same cell types in different stages (for example, A,B, C) in two tissues. After running SCORPIUS, I got the cell orderings of this two datasets are opposite, one is A to C, the other is C to A.  So, I am not sure how to interpret this direction. 
It will be great if you could give me some guide. Many thanks! Best, /Sherry

**Comment by rcannood** [comment]
Hello Sherry,

The direction of the trajectory is definitely NOT meaningful :) It is recommended to look at the expression values with a heatmap and then reverse trajectory if necessary (`reverse_trajectory(traj)`). 

Kind regards,
Robrecht

**Comment by sherriying** [comment]
Hi Robrecht, 

Thanks for your quick response! May I ask more about the algorithm behind to sort the cells around 0 or 1 (trajectory score)? Thanks again! Best,/Sherry

**Comment by rcannood** [comment]
Sure! What do you want to know?

**Comment by sherriying** [comment]
Much appreciated! And congratulations for your fruitful work!
Best,/Sherry

**Comment by rcannood** [comment]
Thank you :)
