### ISSUE TITLE
Can Scorpius handle scaled residuals as input?

### ISSUE THREAD

**Issue by violehtone** [rcannood/SCORPIUS#23]
Hi!

I was wondering that is Scorpius capable of handling scaled and centered expression data (residuals)? In more detail, what I'm looking for is that can I regress out the cell cycle effect (i.e. by following the Seurat tutorial at: https://satijalab.org/seurat/v3.2/cell_cycle_vignette.html) prior to performing trajectory inference and then use this data (scaled residuals) as an input for Scorpius?

Thank you already beforehand!

**Comment by rcannood** [comment]
Hello Ville! 

This should not be a problem at all :) Just plop it in the 'reduce_dimensionality(...)' function as with unscaled expression data.

Kind regards,
Robrecht

**Comment by violehtone** [comment]
Hi Robrecht,

Thank you for the prompt answer and great to hear that Scorpius can handle multiple types of input data! :)

Br, Ville
