### ISSUE TITLE
Providing a custom color palette for row annotations in the draw_trajectory_heatmap function

### ISSUE THREAD

**Issue by violehtone** [rcannood/SCORPIUS#24]
Hi,

I was wondering if it would be somehow possible to add an extra argument to the `draw_trajectory_heatmap` function so that it would allow me to use a custom color palette for row annotations.

Currently, if I pass `annotation_row` argument to the function, it uses by default 8(?) different colors and only the modification of the progression group color palette is possible. Providing a custom palette through `annotation_colors` argument seems not to be possible as the `draw_trajectory_heatmap` function already provides this argument to `pheatmap` function. For instance in my case, in addition to the progression groups of cells, I have also grouped my genes into ~30 different metabolic modules and I would like to annotate the rows based on the assigned module of each gene so that each module would have a distinct color :blush: 

Thank you already beforehand!

Br, Ville Lehtonen

**Comment by rcannood** [comment]
Hello Ville,

Thanks for your feedback. This is a parameter I would need to add to the function. 

I'll let you know when I've made the required changes =)

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Thanks, this feature was added in SCORPIUS 1.0.8!
