### ISSUE TITLE
SCTransform normalised data with SCORPIUS

### ISSUE THREAD

**Issue by lucygarner** [rcannood/SCORPIUS#28]
Hi,

I was wondering whether you have tested data normalised using the SCTransform algorithm with SCORPIUS and whether this works well, or whether you would recommend using log1p normalised data instead?

Best wishes,
Lucy

**Comment by rcannood** [comment]
Hi Lucy, 

Happy new year! One of my new year resolutions... catching up with mails :)

The SCTransform should work just fine (if not better) than the log1p transformation. 

Does this answer your question?

Kind regards,
Robrecht

**Comment by lc822** [comment]
Thanks - good to know. I have tested both and I appear to get "better" results with the log1p transformed data. While the results are fairly similar, my activation trajectories appear more squished when I used the SCTransformed data.

**Comment by rcannood** [comment]
:+1: !
