### ISSUE TITLE
Using tSNE cell embedding values for infer_trajectory

### ISSUE THREAD

**Issue by chitopia** [rcannood/SCORPIUS#29]
Hi,
I'm trying to inference trajectory using the SCORPIUS package in my Seurat object, and I have one question.
Can I use the tSNE cell embedding value of the Seurat object as input of the infer_trajectory function instead of calculating dimensionality? 

I ran infer_trajectory using 2 values and got the following results.

```javascript
# cluster = subgroup of fibroblast

space <- reduce_dimensionality(Fibroblast[['SCT']]@data , dist = "spearman", ndim = 2)
traj <- infer_trajectory(space)
draw_trajectory_plot(space, progression_group = Fibroblast$seurat_clusters, path = traj$path, contour = T)

# DEG
draw_trajectory_heatmap(expr_sel, traj$time, Fibroblast$seurat_clusters, show_labels_row = T, modules)
```
![image](https://user-images.githubusercontent.com/82918288/119299625-38de2480-bc9a-11eb-8e7c-6dd408075bf6.png)

```javascript
space <- Fibroblast@reductions$tsne@cell.embeddings
tsne.traj <- infer_trajectory(space)
draw_trajectory_plot(space, progression_group = Fibroblast$seurat_clusters, path = tsne.traj$path, contour = T)

# DEG
draw_trajectory_heatmap(expr_sel, tsne.traj$time, Fibroblast$seurat_clusters, show_labels_row = T, modules)
```
![image](https://user-images.githubusercontent.com/82918288/119300243-65467080-bc9b-11eb-9a81-367052e2e524.png)

The result using tSNE values looks better, but I'm worried that this way is correct.

I would like to ask your advice on this result.

HY

**Comment by rcannood** [comment]
Technically you can use tSNE (as you nicely demonstrated), although tSNE is not well suited for trajectory inference since it optimises local distances and not global distances. Hope this answers your question!

**Comment by chitopia** [comment]
Thank you for your response! 
If so, how about UMAP values instead of tSNE...?
As far as I know, UMAP might be preserved global distance, unlike tSNE.
Is that possible...?

**Comment by chitopia** [comment]
> 안녕하세요,
> 저는 Seurat 객체에서 SCORPIUS 패키지를 사용하여 궤적을 추론하려고하는데 질문이 하나 있습니다.
> 차원을 계산하는 대신 Seurat 객체의 tSNE 셀 임베딩 값을 infer_trajectory 함수의 입력으로 사용할 수 있습니까?
> 
> 2 개의 값을 사용하여 infer_trajectory를 실행하고 다음과 같은 결과를 얻었습니다.
> 
> ```js
> # 클러스터  =  하위 그룹  의  섬유 아세포
> 
> 공간  < -  reduce_dimensionality ( 섬유 아세포 [ [ 'SCT' ] ] @ 데이터  ,  DIST  =  "스피어" ,  ndim  =  2 ) 
> traj  < -  infer_trajectory ( 공간 ) 
> draw_trajectory_plot ( 공간 ,  progression_group  =  섬유 아세포 $ seurat_clusters ,  경로  =  traj $으로 경로 ,  컨투어  =  T )
> 
> # DEG 
> draw_trajectory_heatmap ( expr_sel ,  traj $ time ,  Fibroblast $ seurat_clusters ,  show_labels_row  =  T ,  modules )
> ```
> 
> ![영상](https://user-images.githubusercontent.com/82918288/119299625-38de2480-bc9a-11eb-8e7c-6dd408075bf6.png)
> 
> ```js
> 공간  < -  섬유 아세포@reductions$tsne@cell.embeddings
> tsne.traj <- infer_trajectory(space)
> draw_trajectory_plot(space, progression_group = Fibroblast$seurat_clusters, path = tsne.traj$path, contour = T)
> 
> # DEG
> draw_trajectory_heatmap(expr_sel, tsne.traj$time, Fibroblast$seurat_clusters, show_labels_row = T, modules)
> ```
> 
> ![영상](https://user-images.githubusercontent.com/82918288/119300243-65467080-bc9b-11eb-9a81-367052e2e524.png)
> 
> The result using tSNE values looks better, but I'm worried that this way is correct.
> 
> I would like to ask your advice on this result.
> 
> HY

**Comment by alikhuseynov** [comment]
..I did it on UMAP (with 2, and 3 components) and LDMS, so trajectory/pseudotime pattern looks largely the same for both.
hope this helps.
