### ISSUE TITLE
ginhoux.R

### ISSUE THREAD

**Issue by doublehelixlf** [rcannood/SCORPIUS#4]
Hi SCORPIUS authors,
I saw your MS on bioRxiv and am very interested in using it for our scRNA-seq experiment. Nevertheless, I did a pre-run using your ginhoux.R file (with the ginhoux dataset), and the heatmap only showed 3 groups. Indeed, it looks quite different from the one shown in the vignette (png is attached). Could you take a look at it, let me know how to reproduce the 6 groups as shown in your paper ?

Thanks and regards,
Feng

![image](https://cloud.githubusercontent.com/assets/13241735/19184043/cff524f8-8cad-11e6-9f9d-e0007006cf66.png)

**Comment by rcannood** [comment]
Dear Feng,

Thank you for your interest in SCORPIUS. The png you attached indeed does not look anything like the figure from the paper. I just re-ran the vignette myself, and got results very similar to those shown in the compiled vignette (https://github.com/rcannood/SCORPIUS/blob/master/vignettes/ginhoux.md). It looks like the genes being plotted are not the genes that are outputted by `gene.importances`. Could you send me the .R file that you used to generate this figure?

Kind regards,
Robrecht

**Comment by doublehelixlf** [comment]
Hi Robrecht,
Thank you for the quick reply! I simply copy-pasted the code provided in your README.md. 

Below is info of R on my computer. 

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

Best,
Feng

**Comment by doublehelixlf** [comment]
Btw, I also ran the ginhoux.Rmd under the folder of Vignette. The result still looks like the one shown above (with 3 groups). As I went through the figures generated, it appears that the path on the trajectory plot is unusual (see below), and a pdf of the output of ginhoux.Rmd is attached here.

Thanks!
[Investigating dendritic cell maturation in dendritic cell progenitors.pdf](https://github.com/rcannood/SCORPIUS/files/515715/Investigating.dendritic.cell.maturation.in.dendritic.cell.progenitors.pdf)





![traj](https://cloud.githubusercontent.com/assets/13241735/19184882/c3d612aa-8cb1-11e6-95b8-dd854479e663.png)

**Comment by rcannood** [comment]
The 'folded' trajectory you attached is not unusual -- in 2D it indeed looks very strange, but in 3D it looks fine: 
```
palette <- setNames(RColorBrewer::brewer.pal(3, "Dark2"), levels(sample.info$group.name))
rgl::plot3d(space, col = palette[sample.info$group.name], size = 5)
rgl::lines3d(traj$path)
```

I still think something is wrong with the results returned by `gene.importances`. After running the script, could you save your environment as an RData file (`save.image("environment.RData")`) and send it to me?

**Comment by doublehelixlf** [comment]
Hi Robrecht,
Please check the following link for an RData file of my last try with SCORPIUS. Thanks!

https://www.dropbox.com/s/pqz0y8y1t18m8vv/ginhoux-test.RData?dl=0

-Feng

**Comment by rcannood** [comment]
There seems to be something wrong with the factors being generated by `gene.importances`.

For a quick fix, you can use `expr.sel <- expression[,as.character(gene.sel$gene)]`. Does this solve your problem?

I'll fix the problem in the package so that the error cannot occur anymore.

**Comment by doublehelixlf** [comment]
Hi Robrecht,
I tried your advice using:
expr.sel <- expression[,as.character(gene.sel)]

That seems to solve the problem. The heatmap now looks nearly the same as the one shown in your updated README. The only difference is that the last run produced 6 modules/groups. 

Thanks any way for your prompt rely. This program looks very promising!

Best,
Feng
