### ISSUE TITLE
reduce_dimensionality change

### ISSUE THREAD

**Issue by anjanbharadwaj** [rcannood/SCORPIUS#9]
Since the package has been updated a bit, I am slightly confused - in reduce_dimensionality, what matrix is passed in? Should I pass in the gene expression matrix, or the distance matrix from correlation_distance? Also, should I just pass in the value _correlation_distance_ for the distance function?

**Comment by anjanbharadwaj** [comment]
In the vignette, the description is "reduce_dimensionality performs an eigenanalysis of the given dissimilarity matrix and returns coordinates of the samples represented in an ndim-dimensional space." From this I would assume we input the distance matrix.

 However, in the example, I see " Reduce the dimensionality of this dataset
space <- reduce_dimensionality(dataset$expression, correlation_distance, ndim = 2)", signifying I should feed in the expression data?

**Comment by rcannood** [comment]
Sorry for the confusion. Calculating the distance matrix separately becomes infeasible for datasets within large numbers of samples. The interface was changed to `reduce_dimensionality(expr, correlation_distance)`. So indeed as you say, first argument is the expression matrix; second is the correlation distance function.

Robrecht

**Comment by anjanbharadwaj** [comment]
Thank you for the clarification!

**Comment by rcannood** [comment]
Thanks for letting me know, I will update the vignette accordingly :)
